- name: Configure sshd and sudoers
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "{{ item.validate | default(omit) }}"
    backup: no
  with_items: "{{ common_node_config_options }}"
  notify: restart ssh
  tags:
    - ssh
    - sudo
    - common

- name: Install firewalld and libselinux-python
  yum:
    name:
      - libselinux-python
      - firewalld
    state: present
  when:
    - "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS'"
    - "ansible_distribution_major_version | int >= 7"
  tags:
    - common

- name: Disable SELinux
  selinux:
    state: permissive
    policy: targeted
  register: selinux_disable
  notify:
    - reboot
    - wait for instance
  tags:
    - common

- meta: flush_handlers
  tags:
    - common
