- block:
  - name: Wait for instances to answer on SSH
    wait_for:
      port: "{{ current_ssh_port }}"
      host: "{{ item.tagged_instances[0].public_ip }}"
      search_regex: OpenSSH
      timeout: 600
    with_items: "{{ instances.results }}"
  rescue:
    - name: Wait for instances to answer on SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.tagged_instances[0].public_ip }}"
        search_regex: OpenSSH
        timeout: 600
      with_items: "{{ instances.results }}"

- name: Set login name
  set_fact:
    login: "{{ ec2_login_names[item.type] }}"
  with_items: "{{ ec2_lab_node_types }}"
  tags:
    - always

- name: Add hosts to control_nodes group
  add_host:
    name: "{{ item.invocation.module_args.instance_tags.Name }}"
    ansible_host: "{{ item.tagged_instances[0].public_ip }}"
    ansible_user: "{{ login }}"
    ansible_port: "{{ ssh_port }}"
    groups: lab_hosts,control_nodes
  with_items: "{{ instances.results }}"
  when: "'control' in item.invocation.module_args.instance_tags.Name"
  changed_when: no
  tags:
    - always

- name: Add hosts to groups
  add_host:
    name: "{{ item.invocation.module_args.instance_tags.Name }}"
    ansible_host: "{{ item.tagged_instances[0].public_ip }}"
    ansible_user: "{{ login }}"
    ansible_port: "{{ ssh_port }}"
    groups: lab_hosts,managed_nodes
  with_items: "{{ instances.results }}"
  when: "'control' not in item.invocation.module_args.instance_tags.Name"
  changed_when: no
  tags:
    - always

- name: Set local username to create on instances
  set_fact:
    username: "{{ item | regex_replace('.*-(\\w*)-\\w*$','\\1') }}"
  with_items: "{{ groups.lab_hosts }}"
  delegate_to: "{{ item }}"
  delegate_facts: yes
  tags:
    - always

- name: Generate student inventories
  template:
    src: instances.txt.j2
    dest: ./{{ item.username }}-instances.txt
  with_items: "{{ users }}"
  tags:
    - inventory
    - users
    - user_accounts

- name: Generate instructor inventory
  template:
    src: instructor_inventory.j2
    dest: ./instructor_inventory.txt
  tags:
    - inventory
    - users
    - user_accounts
