- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    current_ssh_port: 22
    ssh_port: 22
  roles:
    - role: manage_ec2_instances
      tags: provision

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  become: yes
  roles:
    - role: user_accounts
      tags:
        - user_accounts
        - users

    - role: common
      tags: common

- name: Configure control node
  hosts: control_nodes
  become: yes
  roles:
    - role: control_node
      tags:
        - control_node
        - control

- name: Email inventory to students
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - role: email
      tags: email
      when: email
