current_ssh_port: 22
ssh_port: 22
user_setup: no
async: no
provision: no
email: no
bootstrap: no
bootstrap_controller: no
install_ansible: yes

instance_types:
  centos7:
    ami_id: ami-af4333cf
    size: t2.micro
    os_type: linux
    disk_space: 10
  centos7-tower:
    ami_id: ami-af4333cf
    size: t2.medium
    os_type: linux
    disk_space: 20
  rhel7:
    ami_id: ami-12663b7a
    size: t2.micro
    os_type: linux
    disk_space: 10
  rhel7-tower:
    ami_id: ami-12663b7a
    size: t2.medium
    os_type: linux
    disk_space: 20

aws_region: us-east-1
vpc_id: vpc-06c9a463
vpc_subnet_id: subnet-a2169ed5
admin_password: changeme123
admin_password_hash: '$6$rounds=100000$W3Cs5AoklPdUV.Yg$hoRZfL/iVGGki9ZHVU2cXXOyb3WgyifTm09/hp5NhmFd0zvFpm3k5tDxJicOKsjS88ZfirsIyF9UAQnvEizPx/'

types:
  - name: control
    type: centos7-tower
  - name: node1
    type: centos7
  - name: node2
    type: centos7
  - name: node3
    type: centos7
  - name: haproxy
    type: centos7
