- name: Create User Group
  group:
    name: "{{ username }}"
    state: present

- name: Create User Account
  user:
    createhome: yes
    group: "{{ username }}"
    name: "{{ username }}"
    shell: /bin/bash
    state: present
    password: "{{ admin_password_hash }}"
